/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package src;

public class jCbc {
  public static SWIGTYPE_p_double new_jarray_double(int nelements) {
    long cPtr = jCbcJNI.new_jarray_double(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_jarray_double(SWIGTYPE_p_double ary) {
    jCbcJNI.delete_jarray_double(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double jarray_double_getitem(SWIGTYPE_p_double ary, int index) {
    return jCbcJNI.jarray_double_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void jarray_double_setitem(SWIGTYPE_p_double ary, int index, double value) {
    jCbcJNI.jarray_double_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_int new_jarray_int(int nelements) {
    long cPtr = jCbcJNI.new_jarray_int(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_jarray_int(SWIGTYPE_p_int ary) {
    jCbcJNI.delete_jarray_int(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int jarray_int_getitem(SWIGTYPE_p_int ary, int index) {
    return jCbcJNI.jarray_int_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
  }

  public static void jarray_int_setitem(SWIGTYPE_p_int ary, int index, int value) {
    jCbcJNI.jarray_int_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_std__string new_jarray_string(int nelements) {
    long cPtr = jCbcJNI.new_jarray_string(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public static void delete_jarray_string(SWIGTYPE_p_std__string ary) {
    jCbcJNI.delete_jarray_string(SWIGTYPE_p_std__string.getCPtr(ary));
  }

  public static String jarray_string_getitem(SWIGTYPE_p_std__string ary, int index) {
    return jCbcJNI.jarray_string_getitem(SWIGTYPE_p_std__string.getCPtr(ary), index);
  }

  public static void jarray_string_setitem(SWIGTYPE_p_std__string ary, int index, String value) {
    jCbcJNI.jarray_string_setitem(SWIGTYPE_p_std__string.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_CbcModel new_jCbcModel() {
    long cPtr = jCbcJNI.new_jCbcModel();
    return (cPtr == 0) ? null : new SWIGTYPE_p_CbcModel(cPtr, false);
  }

  public static SWIGTYPE_p_CbcModel copy_jCbcModel(SWIGTYPE_p_CbcModel value) {
    long cPtr = jCbcJNI.copy_jCbcModel(SWIGTYPE_p_CbcModel.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_CbcModel(cPtr, false);
  }

  public static void delete_jCbcModel(SWIGTYPE_p_CbcModel obj) {
    jCbcJNI.delete_jCbcModel(SWIGTYPE_p_CbcModel.getCPtr(obj));
  }

  public static void jCbcModel_assign(SWIGTYPE_p_CbcModel obj, SWIGTYPE_p_CbcModel value) {
    jCbcJNI.jCbcModel_assign(SWIGTYPE_p_CbcModel.getCPtr(obj), SWIGTYPE_p_CbcModel.getCPtr(value));
  }

  public static SWIGTYPE_p_CbcModel jCbcModel_value(SWIGTYPE_p_CbcModel obj) {
    return new SWIGTYPE_p_CbcModel(jCbcJNI.jCbcModel_value(SWIGTYPE_p_CbcModel.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_CoinModel new_jCoinModel() {
    long cPtr = jCbcJNI.new_jCoinModel();
    return (cPtr == 0) ? null : new SWIGTYPE_p_CoinModel(cPtr, false);
  }

  public static SWIGTYPE_p_CoinModel copy_jCoinModel(SWIGTYPE_p_CoinModel value) {
    long cPtr = jCbcJNI.copy_jCoinModel(SWIGTYPE_p_CoinModel.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_CoinModel(cPtr, false);
  }

  public static void delete_jCoinModel(SWIGTYPE_p_CoinModel obj) {
    jCbcJNI.delete_jCoinModel(SWIGTYPE_p_CoinModel.getCPtr(obj));
  }

  public static void jCoinModel_assign(SWIGTYPE_p_CoinModel obj, SWIGTYPE_p_CoinModel value) {
    jCbcJNI.jCoinModel_assign(SWIGTYPE_p_CoinModel.getCPtr(obj), SWIGTYPE_p_CoinModel.getCPtr(value));
  }

  public static SWIGTYPE_p_CoinModel jCoinModel_value(SWIGTYPE_p_CoinModel obj) {
    return new SWIGTYPE_p_CoinModel(jCbcJNI.jCoinModel_value(SWIGTYPE_p_CoinModel.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_OsiClpSolverInterface new_jOsiClpSolverInterface() {
    long cPtr = jCbcJNI.new_jOsiClpSolverInterface();
    return (cPtr == 0) ? null : new SWIGTYPE_p_OsiClpSolverInterface(cPtr, false);
  }

  public static SWIGTYPE_p_OsiClpSolverInterface copy_jOsiClpSolverInterface(SWIGTYPE_p_OsiClpSolverInterface value) {
    long cPtr = jCbcJNI.copy_jOsiClpSolverInterface(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_OsiClpSolverInterface(cPtr, false);
  }

  public static void delete_jOsiClpSolverInterface(SWIGTYPE_p_OsiClpSolverInterface obj) {
    jCbcJNI.delete_jOsiClpSolverInterface(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(obj));
  }

  public static void jOsiClpSolverInterface_assign(SWIGTYPE_p_OsiClpSolverInterface obj, SWIGTYPE_p_OsiClpSolverInterface value) {
    jCbcJNI.jOsiClpSolverInterface_assign(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(obj), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(value));
  }

  public static SWIGTYPE_p_OsiClpSolverInterface jOsiClpSolverInterface_value(SWIGTYPE_p_OsiClpSolverInterface obj) {
    return new SWIGTYPE_p_OsiClpSolverInterface(jCbcJNI.jOsiClpSolverInterface_value(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_CoinPackedMatrix new_jCoinPackedMatrix() {
    long cPtr = jCbcJNI.new_jCoinPackedMatrix();
    return (cPtr == 0) ? null : new SWIGTYPE_p_CoinPackedMatrix(cPtr, false);
  }

  public static SWIGTYPE_p_CoinPackedMatrix copy_jCoinPackedMatrix(SWIGTYPE_p_CoinPackedMatrix value) {
    long cPtr = jCbcJNI.copy_jCoinPackedMatrix(SWIGTYPE_p_CoinPackedMatrix.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_CoinPackedMatrix(cPtr, false);
  }

  public static void delete_jCoinPackedMatrix(SWIGTYPE_p_CoinPackedMatrix obj) {
    jCbcJNI.delete_jCoinPackedMatrix(SWIGTYPE_p_CoinPackedMatrix.getCPtr(obj));
  }

  public static void jCoinPackedMatrix_assign(SWIGTYPE_p_CoinPackedMatrix obj, SWIGTYPE_p_CoinPackedMatrix value) {
    jCbcJNI.jCoinPackedMatrix_assign(SWIGTYPE_p_CoinPackedMatrix.getCPtr(obj), SWIGTYPE_p_CoinPackedMatrix.getCPtr(value));
  }

  public static SWIGTYPE_p_CoinPackedMatrix jCoinPackedMatrix_value(SWIGTYPE_p_CoinPackedMatrix obj) {
    return new SWIGTYPE_p_CoinPackedMatrix(jCbcJNI.jCoinPackedMatrix_value(SWIGTYPE_p_CoinPackedMatrix.getCPtr(obj)), true);
  }

  public static void addCol(SWIGTYPE_p_CoinModel build, double collb, double colub, double obj, String name, boolean isInt) {
    jCbcJNI.addCol(SWIGTYPE_p_CoinModel.getCPtr(build), collb, colub, obj, name, isInt);
  }

  public static void addRows(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_CoinModel build) {
    jCbcJNI.addRows__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_CoinModel.getCPtr(build));
  }

  public static void addRow(SWIGTYPE_p_CoinModel build, int numberInRow, SWIGTYPE_p_int index, SWIGTYPE_p_double values, double rowlb, double rowup, String name) {
    jCbcJNI.addRow(SWIGTYPE_p_CoinModel.getCPtr(build), numberInRow, SWIGTYPE_p_int.getCPtr(index), SWIGTYPE_p_double.getCPtr(values), rowlb, rowup, name);
  }

  public static void branchAndBound(SWIGTYPE_p_CbcModel model) {
    jCbcJNI.branchAndBound(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static void readMps(SWIGTYPE_p_CbcModel model, String name) {
    jCbcJNI.readMps__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), name);
  }

  public static void readLp(SWIGTYPE_p_CbcModel model, String name) {
    jCbcJNI.readLp__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), name);
  }

  public static void writeMps(SWIGTYPE_p_CbcModel model, String name) {
    jCbcJNI.writeMps__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), name);
  }

  public static void writeLp(SWIGTYPE_p_CbcModel model, String name) {
    jCbcJNI.writeLp__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), name);
  }

  public static SWIGTYPE_p_double getSol(SWIGTYPE_p_CbcModel model) {
    long cPtr = jCbcJNI.getSol(SWIGTYPE_p_CbcModel.getCPtr(model));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void setInteger(SWIGTYPE_p_CbcModel model, int i) {
    jCbcJNI.setInteger__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), i);
  }

  public static void addRows(SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_CoinModel build) {
    jCbcJNI.addRows__SWIG_1(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_CoinModel.getCPtr(build));
  }

  public static void assignSolver(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver) {
    jCbcJNI.assignSolver(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static void readMps(SWIGTYPE_p_OsiClpSolverInterface solver, String name) {
    jCbcJNI.readMps__SWIG_1(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), name);
  }

  public static void readLp(SWIGTYPE_p_OsiClpSolverInterface solver, String name) {
    jCbcJNI.readLp__SWIG_1(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), name);
  }

  public static void setInteger(SWIGTYPE_p_OsiClpSolverInterface solver, int i) {
    jCbcJNI.setInteger__SWIG_1(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), i);
  }

  public static void initialSolve(SWIGTYPE_p_OsiClpSolverInterface solver) {
    jCbcJNI.initialSolve(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static void setLogLevel(SWIGTYPE_p_OsiClpSolverInterface solver, int i) {
    jCbcJNI.setLogLevel__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), i);
  }

  public static void setLogLevel(SWIGTYPE_p_CbcModel model, int i) {
    jCbcJNI.setLogLevel__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), i);
  }

  public static void writeMps(SWIGTYPE_p_OsiClpSolverInterface solver, String name) {
    jCbcJNI.writeMps__SWIG_1(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), name);
  }

  public static void writeLp(SWIGTYPE_p_OsiClpSolverInterface solver, String name) {
    jCbcJNI.writeLp__SWIG_1(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), name);
  }

  public static void solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, int logLevel) {
    jCbcJNI.solve__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), logLevel);
  }

  public static void solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver) {
    jCbcJNI.solve__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static void solve_1(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, int logLevel) {
    jCbcJNI.solve_1__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), logLevel);
  }

  public static void solve_1(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver) {
    jCbcJNI.solve_1__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static int solve_2(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, int logLevel) {
    return jCbcJNI.solve_2__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), logLevel);
  }

  public static int solve_2(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.solve_2__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static int solve_3(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, int logLevel, double presolve_tolerance) {
    return jCbcJNI.solve_3__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), logLevel, presolve_tolerance);
  }

  public static int solve_3(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, int logLevel) {
    return jCbcJNI.solve_3__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), logLevel);
  }

  public static int solve_3(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.solve_3__SWIG_2(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static int isInteger(SWIGTYPE_p_OsiClpSolverInterface solver, int i) {
    return jCbcJNI.isInteger__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), i);
  }

  public static int isInteger(SWIGTYPE_p_CbcModel model, int i) {
    return jCbcJNI.isInteger__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), i);
  }

  public static String getRowName(SWIGTYPE_p_OsiClpSolverInterface solver, int i) {
    return jCbcJNI.getRowName__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), i);
  }

  public static String getColName(SWIGTYPE_p_OsiClpSolverInterface solver, int i) {
    return jCbcJNI.getColName__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), i);
  }

  public static String getRowName(SWIGTYPE_p_CbcModel model, int i) {
    return jCbcJNI.getRowName__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), i);
  }

  public static String getColName(SWIGTYPE_p_CbcModel model, int i) {
    return jCbcJNI.getColName__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), i);
  }

  public static int getNumRows(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getNumRows__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static int getNumCols(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getNumCols__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static int getNumRows(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.getNumRows__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static int getNumCols(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.getNumCols__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static SWIGTYPE_p_double getColSolution(SWIGTYPE_p_OsiClpSolverInterface solver) {
    long cPtr = jCbcJNI.getColSolution__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double getRowPrice(SWIGTYPE_p_OsiClpSolverInterface solver) {
    long cPtr = jCbcJNI.getRowPrice__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double getRowActivity(SWIGTYPE_p_OsiClpSolverInterface solver) {
    long cPtr = jCbcJNI.getRowActivity__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double getReducedCost(SWIGTYPE_p_OsiClpSolverInterface solver) {
    long cPtr = jCbcJNI.getReducedCost__SWIG_0(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double getColSolution(SWIGTYPE_p_CbcModel model) {
    long cPtr = jCbcJNI.getColSolution__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double getRowPrice(SWIGTYPE_p_CbcModel model) {
    long cPtr = jCbcJNI.getRowPrice__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double getRowActivity(SWIGTYPE_p_CbcModel model) {
    long cPtr = jCbcJNI.getRowActivity__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double getReducedCost(SWIGTYPE_p_CbcModel model) {
    long cPtr = jCbcJNI.getReducedCost__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model));
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static int numberIntegers(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.numberIntegers(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static double getObjValue(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.getObjValue__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static int status(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.status(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static int isProvenOptimal(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.isProvenOptimal(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static int isProvenInfeasible(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.isProvenInfeasible(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static void setModelName(SWIGTYPE_p_OsiClpSolverInterface solver, String name) {
    jCbcJNI.setModelName(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), name);
  }

  public static String getModelName(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getModelName(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static int isBinary(SWIGTYPE_p_OsiClpSolverInterface solver, int i) {
    return jCbcJNI.isBinary(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), i);
  }

  public static int secondaryStatus(SWIGTYPE_p_CbcModel model) {
    return jCbcJNI.secondaryStatus(SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static double getCoinCpuTime() {
    return jCbcJNI.getCoinCpuTime();
  }

  public static double getObjValue(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getObjValue__SWIG_1(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static void setRowName(SWIGTYPE_p_OsiClpSolverInterface solver, int i, String name) {
    jCbcJNI.setRowName(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), i, name);
  }

  public static void setPrimalTolerance(SWIGTYPE_p_CbcModel model, double a) {
    jCbcJNI.setPrimalTolerance(SWIGTYPE_p_CbcModel.getCPtr(model), a);
  }

  public static void setDualTolerance(SWIGTYPE_p_CbcModel model, double a) {
    jCbcJNI.setDualTolerance(SWIGTYPE_p_CbcModel.getCPtr(model), a);
  }

  public static void setIntegerTolerance(SWIGTYPE_p_CbcModel model, double a) {
    jCbcJNI.setIntegerTolerance(SWIGTYPE_p_CbcModel.getCPtr(model), a);
  }

  public static int solve_whs(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, int logLevel, double presolve_tolerance) {
    return jCbcJNI.solve_whs__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, logLevel, presolve_tolerance);
  }

  public static int solve_whs(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, int logLevel) {
    return jCbcJNI.solve_whs__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, logLevel);
  }

  public static int solve_whs(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars) {
    return jCbcJNI.solve_whs__SWIG_2(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars);
  }

  public static int getNumIntegers(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getNumIntegers(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static void writeLp1(SWIGTYPE_p_CbcModel model, String name, double epsilon, int decimals) {
    jCbcJNI.writeLp1__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), name, epsilon, decimals);
  }

  public static void writeLp1(SWIGTYPE_p_CbcModel model, String name, double epsilon) {
    jCbcJNI.writeLp1__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), name, epsilon);
  }

  public static void writeLp1(SWIGTYPE_p_CbcModel model, String name) {
    jCbcJNI.writeLp1__SWIG_2(SWIGTYPE_p_CbcModel.getCPtr(model), name);
  }

  public static void writeMps1(SWIGTYPE_p_CbcModel model, String name, int formatType, int numberAcross, double objSense) {
    jCbcJNI.writeMps1__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), name, formatType, numberAcross, objSense);
  }

  public static void writeMps1(SWIGTYPE_p_CbcModel model, String name, int formatType, int numberAcross) {
    jCbcJNI.writeMps1__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), name, formatType, numberAcross);
  }

  public static void writeMps1(SWIGTYPE_p_CbcModel model, String name, int formatType) {
    jCbcJNI.writeMps1__SWIG_2(SWIGTYPE_p_CbcModel.getCPtr(model), name, formatType);
  }

  public static void writeMps1(SWIGTYPE_p_CbcModel model, String name) {
    jCbcJNI.writeMps1__SWIG_3(SWIGTYPE_p_CbcModel.getCPtr(model), name);
  }

  public static void callCbc(String a, SWIGTYPE_p_CbcModel model) {
    jCbcJNI.callCbc(a, SWIGTYPE_p_CbcModel.getCPtr(model));
  }

  public static void setMaximumNodes(SWIGTYPE_p_CbcModel model, int value) {
    jCbcJNI.setMaximumNodes(SWIGTYPE_p_CbcModel.getCPtr(model), value);
  }

  public static void setNumberThreads(SWIGTYPE_p_CbcModel model, int a) {
    jCbcJNI.setNumberThreads(SWIGTYPE_p_CbcModel.getCPtr(model), a);
  }

  public static void setThreadMode(SWIGTYPE_p_CbcModel model, int a) {
    jCbcJNI.setThreadMode(SWIGTYPE_p_CbcModel.getCPtr(model), a);
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, SWIGTYPE_p_std__string names1, SWIGTYPE_p_int values1, int intvars1, SWIGTYPE_p_std__string names2, SWIGTYPE_p_int values2, int intvars2) {
    jCbcJNI.par_solve__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, SWIGTYPE_p_std__string.getCPtr(names1), SWIGTYPE_p_int.getCPtr(values1), intvars1, SWIGTYPE_p_std__string.getCPtr(names2), SWIGTYPE_p_int.getCPtr(values2), intvars2);
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, SWIGTYPE_p_std__string names1, SWIGTYPE_p_int values1, int intvars1, SWIGTYPE_p_std__string names2, SWIGTYPE_p_int values2) {
    jCbcJNI.par_solve__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, SWIGTYPE_p_std__string.getCPtr(names1), SWIGTYPE_p_int.getCPtr(values1), intvars1, SWIGTYPE_p_std__string.getCPtr(names2), SWIGTYPE_p_int.getCPtr(values2));
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, SWIGTYPE_p_std__string names1, SWIGTYPE_p_int values1, int intvars1, SWIGTYPE_p_std__string names2) {
    jCbcJNI.par_solve__SWIG_2(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, SWIGTYPE_p_std__string.getCPtr(names1), SWIGTYPE_p_int.getCPtr(values1), intvars1, SWIGTYPE_p_std__string.getCPtr(names2));
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, SWIGTYPE_p_std__string names1, SWIGTYPE_p_int values1, int intvars1) {
    jCbcJNI.par_solve__SWIG_3(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, SWIGTYPE_p_std__string.getCPtr(names1), SWIGTYPE_p_int.getCPtr(values1), intvars1);
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, SWIGTYPE_p_std__string names1, SWIGTYPE_p_int values1) {
    jCbcJNI.par_solve__SWIG_4(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, SWIGTYPE_p_std__string.getCPtr(names1), SWIGTYPE_p_int.getCPtr(values1));
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, SWIGTYPE_p_std__string names1) {
    jCbcJNI.par_solve__SWIG_5(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, SWIGTYPE_p_std__string.getCPtr(names1));
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars) {
    jCbcJNI.par_solve__SWIG_6(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars);
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values) {
    jCbcJNI.par_solve__SWIG_7(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values));
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s, SWIGTYPE_p_std__string names) {
    jCbcJNI.par_solve__SWIG_8(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s, SWIGTYPE_p_std__string.getCPtr(names));
  }

  public static void par_solve(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, String s) {
    jCbcJNI.par_solve__SWIG_9(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), s);
  }

  public static void cutoff(SWIGTYPE_p_CbcModel model, int n) {
    jCbcJNI.cutoff(SWIGTYPE_p_CbcModel.getCPtr(model), n);
  }

  public static int solve_unified(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars, int logLevel) {
    return jCbcJNI.solve_unified__SWIG_0(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars, logLevel);
  }

  public static int solve_unified(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values, int intvars) {
    return jCbcJNI.solve_unified__SWIG_1(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values), intvars);
  }

  public static int solve_unified(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_std__string names, SWIGTYPE_p_int values) {
    return jCbcJNI.solve_unified__SWIG_2(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_std__string.getCPtr(names), SWIGTYPE_p_int.getCPtr(values));
  }

  public static int solve_unified(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver, SWIGTYPE_p_std__string names) {
    return jCbcJNI.solve_unified__SWIG_3(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver), SWIGTYPE_p_std__string.getCPtr(names));
  }

  public static int solve_unified(SWIGTYPE_p_CbcModel model, SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.solve_unified__SWIG_4(SWIGTYPE_p_CbcModel.getCPtr(model), SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static double getMinRHS(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getMinRHS(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static double getMinCoeff(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getMinCoeff(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

  public static double getMaxCoeff(SWIGTYPE_p_OsiClpSolverInterface solver) {
    return jCbcJNI.getMaxCoeff(SWIGTYPE_p_OsiClpSolverInterface.getCPtr(solver));
  }

}
