/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package src;

public class SWIGTYPE_p_CbcModel {
  private transient long swigCPtr;

  protected SWIGTYPE_p_CbcModel(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_CbcModel() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_CbcModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

